TreisPro/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('treisApp.urls')),
    path('',include('percapitaApp.urls',namespace='percapitaApp'))
]  
if settings.DEBUG:
    pass
    #urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)
    #urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)

percapitaApp/urls.py
from .import views
from django.urls import path

app_name = 'percapitaApp'
urlpatterns = [
    path('percapita/',views.purchaseView,name='percapita'),
    path('itemsinserted/',views.purchaseItemsInfo,name='itemsinfo'),
]

treisApp/urls.py
from os import name
from django import views
from .models import Student
from .import views
from django.urls import path
urlpatterns = [
    path('',views.homeView,name='home'),
    path('login/',views.loginView,name='loginview'),
    path('logout/',views.logoutPage,name='logoutpage'),
    path('student/',views.studentView,name='student'),
    path('studReport/',views.students_view,name='studentsreport'),
    path('marks/',views.marksView,name="marksentry"),
    #path('studentlist/',views.studentList,name="studentList"),
    path('marksentry/',views.marksEntry,name="marks"),
    #path('marksreport/',views.marksReport,name="marksreport"),
    path('markslist/',views.marksList,name="markslist"),
    path('studentupdat/<int:pk>/',views.update_student_view,name='studupdate'),
    path('studentdelete/<int:pk>/',views.student_delete,name='studentdelete'),
]

treisApp/models.py
from datetime import date
from operator import mod
from os import access
from random import choices
from unicodedata import name
#from tkinter import CASCADE, CURRENT
from django.contrib.auth.models import User
from django.db import models
from django.http import request

class Student(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    name = models.CharField(max_length=100)
    fathername = models.CharField(max_length=200,null=True)
    dob = models.DateField(null=True)
    ay = (('21','2021-2022'),
            ('22','2022-2023'),
            ('23','2023-2024'),)
    academicyear = models.CharField(max_length=100, choices = ay, default='2021-2022',null=True)
    y = (('I Year', 'I Year'),
                ('II Year','II Year'),)
    year = models.CharField(max_length=50,choices=y, null=True)
    g = (('MPC','MPC'),
        ('BPC','BPC'),
        ('MEC','MEC'),)
    group = models.CharField(max_length=100,choices=g,null=True)
    address = models.CharField(max_length=100,null=True)
    def __str__(self):
        return self.name
class Marks(models.Model):
    name = models.ForeignKey(Student,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    year = models.CharField(max_length=100,null=True)
    group = models.CharField(max_length=100,null=True)
    testtype = models.CharField(max_length=100,null=True)
    ac = models.CharField(max_length=20,null=True)
    s1 = models.IntegerField()
    s2 = models.IntegerField()
    s3 = models.IntegerField()
    s4 = models.IntegerField()
    s5 = models.IntegerField()
    s6 = models.IntegerField()
    def __str__(self):
        return self.name

treisApp/forms.py
from dataclasses import fields
from logging import PlaceHolder
from multiprocessing.sharedctypes import Value
#from tkinter import Widget
from django.contrib.auth.models import User
from django import forms
from django.forms import HiddenInput, ModelForm,DateInput, PasswordInput, widgets
from django.http import request
from .models import Student

class DateInput(forms.DateInput):
    input_type = 'date'


class StudentForm(ModelForm):
    class Meta:
        model = Student
        exclude = ['user']
        widgets = {
            'dob': DateInput()
        } 
class loginForm(ModelForm):
    class Meta:
        model = User
        fields = ['username','password']
        widgets = {
            'password': PasswordInput(),
        }
        

treisApp/views.py
from django.http import HttpResponse, request
from django.http import response
from django.shortcuts import render,redirect
from .forms import StudentForm,loginForm
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from .models import Marks, Student
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from copy import deepcopy
from django.contrib import messages
# Create your views here.

def loginView(request):
    #form = loginForm()
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            user = User.objects.get(username=username)
        except:
            return HttpResponse('User Not Exist')
        user = authenticate(request,username=username,password=password)
        if user is not None:
            login(request,user)
            return redirect(homeView)
    else:
        return render(request,'login.html',{})
def logoutPage(request):
    logout(request)
    return redirect(homeView)

def studentView(request):
    if request.method == "POST":
        user = User.objects.get(id=request.user.id)
        name = request.POST['name']
        fathername = request.POST['fathername']
        dob = request.POST['dob']
        ac = '21'
        year = request.POST['year']
        group = request.POST['group']
        address = request.POST['address']
        print(year)
        Student.objects.create(user=user,name=name,fathername=fathername,dob=dob,academicyear=ac,year=year,group=group,address=address)
        messages.info(request,"Student Data Inserted")
        return redirect(homeView)         
    else:
        return render(request,'student.html',{})


def students_view(request):
    if request.method == 'POST':
        y = request.POST.get('year')
        g = request.POST.get('group')
        try:
            students = Student.objects.filter(year=y,group=g,user_id=request.user.id)
        except:
            raise ConnectionAbortedError
        print(y,g,students,request.user.id)
        return render(request,'studentslist.html',{'forms':students})
    else:
        request.session['pa']=1
        return render(request,'student_display.html',{})

'''
def studentList(request):
    if request.method == 'GET':
        y = request.GET.get('year')
        g = request.GET.get('group')
        print(y,g,request.user.id)
        students = Student.objects.filter(year=y, group=g, user_id=request.user.id)
        stu = deepcopy(students)
        p = Paginator(stu,3)
        page_request_var = "page"
        page_number = request.GET.get('page_request_var')
        print(page_number)
        page_obj = p.get_page(page_number)
        try:
            page_obj = p.get_page(page_number)
        except PageNotAnInteger:
            page_obj = p.page(1)
        except EmptyPage:
            page_obj = p.page(p.num_pages)
        context = {'page_obj': page_obj,
        'page_request_var':page_request_var}
        #print(dir(p))
        print(request.GET)
        #print(page_obj.object_list)
        print(p.num_pages)
        print(y)
        print(students)
        return render(request,'studentslist.html',{'students':students})
        #return render(request,'studentslist.html',context)

'''
def homeView(request):
    return render(request,'home.html',{})
def marksView(request):
    return render(request,"studentsmarks.html",{})


def marksEntry(request):
    form = Student.objects.filter(user_id=request.user.id, year=request.GET.get('year'),
    group=request.GET.get('group'))
    if request.method == 'POST':
        for i in range(1,len(form)+1):
            name = form[i-1]
            user = User.objects.get(id=request.user.id)
            year = request.GET.get('year')
            group = request.GET.get('group')
            test = request.GET.get('test')
            ac = Student.objects.filter(user_id=request.user.id).values()[0]['academicyear']
            print(ac)
            if group == 'MPC':
                E = request.POST.get('E'+str(i)+'')
                S = request.POST.get('S'+str(i)+'')
                MA = request.POST.get('MA'+str(i)+'')
                MB = request.POST.get('MB'+str(i)+'')
                P = request.POST.get('P'+str(i)+'')
                C = request.POST.get('C'+str(i)+'')
                Marks.objects.create(name=name,user=user,year=year,group=group,testtype=test,ac=ac,s1=E,s2=S,s3=MA,s4=MB,s5=P,s6=C)
            elif group == 'BPC':
                E = request.POST.get('E'+str(i)+'')
                S = request.POST.get('S'+str(i)+'')
                MA = request.POST.get('BO'+str(i)+'')
                MB = request.POST.get('ZO'+str(i)+'')
                P = request.POST.get('BP'+str(i)+'')
                C = request.POST.get('BC'+str(i)+'')
                Marks.objects.create(name=name,user=user,year=year,group=group,testtype=test,ac=ac,s1=E,s2=S,s3=MA,s4=MB,s5=P,s6=C)
            else:   
                E = request.POST.get('E'+str(i)+'')
                S = request.POST.get('S'+str(i)+'')
                MA = request.POST.get('EMA'+str(i)+'')
                MB = request.POST.get('EMB'+str(i)+'')
                P = request.POST.get('ECO'+str(i)+'')
                C = request.POST.get('COMM'+str(i)+'')
                Marks.objects.create(name=name,user=user,year=year,group=group,testtype=test,ac=ac,s1=E,s2=S,s3=MA,s4=MB,s5=P,s6=C)
        messages.info(request,f"Marks of {year} {group} {test} Inserted Successfully!")        
        return redirect(homeView)
    else:
        g = request.GET.get('group')
        if Marks.objects.filter(user_id=request.user.id,group=request.GET.get('group'),testtype=request.GET.get('test'),
        year=request.GET.get('year')):
            return render(request,'marksalreadyentered.html',{})
        elif g =='MPC': 
            return render(request,'marks.html',{'form':form})
        elif g =='BPC':
            return render(request,'marksbpc.html',{'form':form})
        else:
            return render(request,'marksmec.html',{'form':form})  

def marksList(request):
    if request.method =="POST":
        y = request.POST.get('year')
        g = request.POST.get('group')
        type = request.POST.get('testtype')
        report = Marks.objects.filter(user_id=request.user.id,year=y,group=g,testtype=type)
        if g =='MPC':
            return render(request,'marksreport.html',{'report':report})
        elif g == 'BPC':
            return render(request,'marksreportbpc.html',{'report':report})
        else:
            return render(request,'marksreportmec.html',{'report':report})
    else:
        return render(request,'markslist.html',{})


def update_student_view(request,pk):
    form = Student.objects.get(id=pk)
    if request.method =='POST':
        form.name = request.POST.get('name')
        form.fathername = request.POST.get('fathername')
        form.dob = request.POST.get('dob')
        form.year = request.POST.get('year')
        form.group = request.POST.get('group')
        form.address = request.POST.get('address')
        form.save()
        return render(request,'studentdetailsupdate.html',{})
    else:
        return render(request,'studentupdate.html',{'form':form})

def student_delete(request,pk):
    form = Student.objects.get(id=pk)
    form.delete()
    return render(request,'studentdelete.html',{})

treisApp/templates/Studentdelete.html
{%extends 'home.html'%}
{%block content%}
<html>
    <div class="container">    
        <h1 class="text-center" style="color: green;">Student Details Deleted Successfully</h1>
    </div>
</html>
{%endblock%}

treisApp/templates/home.html
{%include 'cdnlines.html'%}
{%load static%}
<html>
    <head>
        <title>TREIS</title>
        <div class="container" style="background-color: rgb(77, 77, 241); border-radius: 25px;">    
            <div style="float: left;">
                <img style="border-radius: 40px;" src="{% static 'logo.png' %}" alt="TREIS LOGO" height="90px" width="90px">
            </div>
            <div style="color: white; font-size: 65px; text-align: center; float: center;">
                <p>TREIS (R), HYDERABAD.</p>
            </div>
        </div>
        <style>
            a {
                font-size: 20px;
                color: white;
            }
            .nav-link{
                color: white;
            }
            .logoutitem {
                float: right;
            }
            .navul {
                float: right;
            }
            .body{
                background-image: "{% static 'body.jpg' %}";
            }
        </style>
    </head>       
    <body class="body">
        <div class="container">
            <nav class="navbar navbar-dark" style="background-color: rebeccapurple">        
                <div style="float: left;">
                    <ul class="nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home' %}">Home</a>
                        </li>
                {%if request.user.is_authenticated %}
                    <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Student Entry
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'student' %}">Student Entry</a></li>
            <li><a class="dropdown-item" href="{% url 'studentsreport' %}">Student Data</a></li>
        </ul>
        </li>
            <!--            
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'student' %}">Student Entry</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'studentsreport' %}">Student Data</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'marksentry' %}">Marks Entry</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'markslist' %}">Marks Report</a>
                        </li>
                    
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'percapitaApp:percapita'%}">Item Purchases</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'percapitaApp:itemsinfo'%}">Items List</a>
                        </li>
                    -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Reports
                        </a>
                        <ul class="dropdown-menu">
                          <li><a class="dropdown-item" href="{% url 'marksentry' %}">Marks Entry</a></li>
                          <li><a class="dropdown-item" href="{% url 'markslist' %}">Marks Report</a></li>
                      </ul>
                      </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Percapita
                            </a>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="{% url 'percapitaApp:percapita'%}">Purchase Entry</a></li>
                              <li><a class="dropdown-item" href="{% url 'percapitaApp:itemsinfo'%}">Stock Details</a></li>
                            </ul>
                          </li>
                    </ul>
                </div>
                    <div style="float: right;">
                        <ul class="nav">                
                            <span class="navbar-text" style="font-size: 20px; color: yellow;">Welcome! {{request.user|capfirst}}</span>
                                <li class="nav-item" style="float: right;">
                                <a class="nav-link" href="{% url 'logoutpage' %}">Logout</a>
                                </li>
                        </ul>
                    </div>
            {%else%}
                </ul>
            </div>
                <div style="float: right;">
                    <ul class="nav">
                        <li class="nav-item" style="float: right;">
                            <a class="nav-link" href="{%url 'loginview' %}">Login</a>
                        </li>
                    </ul>
                </div>
            {%endif%} 
            </nav>
            <br>
            {% if messages %}
            <ul>
            {% for message in messages %}
            <h1 style="color: green;">
            <li {% if message.tags %} class="{{message.tags}}" {%endif%}>
            {{message}}</h1>
            </li>
            {%endfor%}
            </ul>
            {%endif%}
        
        </div>
    {%block content%}


    {%endblock%}
    </body>
</html>

treisApp/templates/marks.html
{%extends 'home.html'%}
{%block content%}
<html>
    <div class="container">
    <head>
        <title>TREIS</title>
        <h1 class="alert-warning text-center">Marks Entry:</h1>
    </head>
    </div>
    <body>
        <div class="container">
            <form method="post">
            {%csrf_token%}
        <table class="table table-bordered table-striped">
            <thead class="text-center">
                <th>SL.No.</td>
                <th>Student Name</td>
                <th>English</td>
                <th>Sanskrit</th>
                <th>Maths-A</th>
                <th>Maths-B</th>
                <th>Physics</th>
                <th>Chemistry</th>
                <th>Total</th>        
            </thead>
            <tbody class="text-center">
                {%for m in form%}
                <tr name="the-row">
                    <td>{{forloop.counter}}</td>
                    <td>{{m.name}}</td>
                    <td><input size="3" type="text" name="E{{forloop.counter}}" id="E{{forloop.counter}}"></td>
                    <td><input size="3" type="text" name="S{{forloop.counter}}" id="S{{forloop.counter}}"></td>
                    <td><input size="3" type="text" name="MA{{forloop.counter}}" id="MA{{forloop.counter}}"></td>
                    <td><input size="3" type="text" name="MB{{forloop.counter}}" id="MB{{forloop.counter}}"></td>
                    <td><input size="3" type="text" name="P{{forloop.counter}}" id="P{{forloop.counter}}"></td>
                    <td><input size="3" type="text" name="C{{forloop.counter}}" id="C{{forloop.counter}}"></td>
                    <td><input size="3" type="text" name="T{{forloop.counter}}" id="T{{forloop.counter}}" readonly></td>
                </tr>
                {%endfor%}
            </tbody>
        </table>
        <br>
        <input type="submit" value="Submit">
        <input type="reset" value="Reset">
    </form>
    {%include 'ajax.html'%}
</div>
</body>
</html>
{%endblock%}

treisApp/templates/marksalreadyentered.html
{%extends 'home.html'%}
{%block content%}
<html>
    <div class="container">    
        <h1 class="text-center" style="color: green;">Marks inserted already</h1>
    </div>
</html>
{%endblock%}

treisApp/templates/marksbpc.html
{%extends 'home.html'%}
{%block content%}
<html>
    <div class="container">
    <head>
        <title>TREIS</title>
        <h1 class="alert-warning text-center">Marks Entry:</h1>
    </head>
    </div>
    <body>
        <div class="container">
            <form method="post">
            {%csrf_token%}
        <table class="table table-bordered table-striped">
            <thead class="text-center">
                <th>SL.No.</td>
                <th>Student Name</td>
                <th>English</td>
                <th>Sanskrit</th>
                <th>Botany</th>
                <th>Zoology</th>
                <th>Physics</th>
                <th>Chemistry</th>
                <th>Total</th>        
            </thead>
            <tbody class="text-center">
                {%for m in form%}
                <tr name="the-row">
                    <td>{{forloop.counter}}</td>
                    <td>{{m.name}}</td>
                    <td><input size="3" type="text" name="E{{forloop.counter}}" id="E{{forloop.counter}}"></td>
                    <td><input size="3" type="text" name="S{{forloop.counter}}" id="S{{forloop.counter}}"></td>
                    <td><input size="3" type="text" name="BO{{forloop.counter}}" id="BO{{forloop.counter}}"></td>
                    <td><input size="3" type="text" name="ZO{{forloop.counter}}" id="ZO{{forloop.counter}}"></td>
                    <td><input size="3" type="text" name="BP{{forloop.counter}}" id="BP{{forloop.counter}}"></td>
                    <td><input size="3" type="text" name="BC{{forloop.counter}}" id="BC{{forloop.counter}}"></td>
                    <td><input size="3" type="text" name="T{{forloop.counter}}" id="T{{forloop.counter}}" readonly></td>
                </tr>
                {%endfor%}
            </tbody>
        </table>
        <br>
        <input type="submit" value="Submit">
        <input type="reset" value="Reset">
    </form>
    {%include 'ajax.html'%}
</div>
</body>
</html>
{%endblock%}

treisApp/templates/marksentry.html
{%extends 'home.html'%}
{%block content%}
<html>
    <div class="container">
    <head>
        <h1 class="text-center alert-info">Students Information</h1>
    </head>
</div>
    <body>
        <div class="container text-center">
        <form method="post" class="form-control">
            {%csrf_token%}
            <label>Select Year:</label>
            <select class="form-select" name="year", id="year">
                <option value="select">Select</option>
                <option value="I year">First Year</option>
                <option value="II year">Second Year</option>
            </select><br>
            <label> Select Group:</label>
                <select class="form-select" name='group' id="group">
                    <option value="select">Select</option>
                    <option value="MPC">MPC</option>
                    <option value="BPC">BPC</option>
                    <option value="MEC">MEC</option>
                </select>
            </label><br>
            <input type="submit" value="Submit">
        </form>
    </div>
</body>
</html>
{%endblock%}

treisApp/templates/markslist.html
{%extends 'home.html'%}
{%block content%}
<html>
    <div class="container">    <head>
        <h1 class="text-center alert-success">Students Marks</h1>
    </head>
</div>

    <body>
        <div class="container">
            <div class="container row">
                <div class="col-md-5"></div>
                <div class="col-md-2">    
            <form method="post">
            {%csrf_token%}
            <label style="font-size: 20px;">Select Year:</label>
            <select class="form-select" name="year", id="year">
                <option value="select">Select</option>
                <option value="I Year">First Year</option>
                <option value="II Year">Second Year</option>
            </select><br>
            <label style="font-size: 20px;"> Select Group:</label>
                <select class="form-select" name='group' id="group">
                    <option value="select">Select</option>
                    <option value="MPC">MPC</option>
                    <option value="BPC">BPC</option>
                    <option value="MEC">MEC</option>
                </select><br>
                <label style="font-size: 20px;"> Test Type:</label>
                <select class="form-select" name='testtype' id="testtype">
                    <option value="select">Select</option>
                    <option value="Unit Test-I">Unit Test-I</option>
                    <option value="Unit Test-II">Unit Test-II</option>
                    <option value="Unit Test-III">Unit Test-III</option>
                    <option value="Grand Test-I">Grand Test-I</option>
                    <option value="Grand Test-II">Grand Test-II</option>
                    <option value="Grand Test-III">Grand Test-III</option>
                    <option value="ipe">ipe</option>
                </select>
                <br>
            <input class="btn btn-primary" type="submit" value="Submit">
        </form>
        </div>           
        </div>
    </body>
{%endblock%}
</html>

treisApp/templates/marksmec.html
{%extends 'home.html'%}
{%block content%}
<html>
    <div class="container">
    <head>
        <title>TREIS</title>
        <h1 class="alert-warning text-center">Marks Entry:</h1>
    </head>
    </div>
    <body>
        <div class="container">
            <form method="post">
            {%csrf_token%}
        <table class="table table-bordered table-striped">
            <thead class="text-center">
                <th>SL.No.</td>
                <th>Student Name</td>
                <th>English</td>
                <th>Sanskrit</th>
                <th>Maths-A</th>
                <th>Maths-B</th>
                <th>Economics</th>
                <th>Commerce</th>
                <th>Total</th>        
            </thead>
            <tbody class="text-center">
                {%for m in form%}
                <tr name="the-row">
                    <td>{{forloop.counter}}</td>
                    <td>{{m.name}}</td>
                    <td><input size="3" type="text" name="E{{forloop.counter}}" id="E{{forloop.counter}}"></td>
                    <td><input size="3" type="text" name="S{{forloop.counter}}" id="S{{forloop.counter}}"></td>
                    <td><input size="3" type="text" name="EMA{{forloop.counter}}" id="EMA{{forloop.counter}}"></td>
                    <td><input size="3" type="text" name="EMB{{forloop.counter}}" id="EMB{{forloop.counter}}"></td>
                    <td><input size="3" type="text" name="ECO{{forloop.counter}}" id="ECO{{forloop.counter}}"></td>
                    <td><input size="3" type="text" name="COMM{{forloop.counter}}" id="COMM{{forloop.counter}}"></td>
                    <td><input size="3" type="text" name="T{{forloop.counter}}" id="T{{forloop.counter}}" readonly></td>
                </tr>
                {%endfor%}
            </tbody>
        </table>
        <br>
        <input type="submit" value="Submit">
        <input type="reset" value="Reset">
    </form>
    {%include 'ajax.html'%}
</div>
</body>
</html>
{%endblock%}

treisApp/templates/marksreport.html
{%extends 'home.html'%}
<html>
{%block content%}
<div class="container">
<head>
    <h1 class="alert-danger text-center">Students Information</h1>
</head>
</div>
<body>
<div class="container">
<table class="table table-bordered text-center">
    <thead>
        <th>SL.No.</th>
        <th>Student Name</th>
        <th>Year</th>
        <th>Group</th>
        <th>English</th>
        <th>Sanskrit</th>
        <th>Maths-A</th>
        <th>Maths-B</th>
        <th>Physics</th>
        <th>Chemistry</th>
        <th>Total</th>
    </thead>
    <tbody>
        {%for i in report%}
        <tr>
            <td class="text-center">{{forloop.counter}}</td>
            <td>{{i.name}}</td>
            <td>{{i.year}}</td>
            <td>{{i.group}}</td>
            <td>{{i.s1}}</td>
            <td>{{i.s2}}</td>
            <td>{{i.s3}}</td>
            <td>{{i.s4}}</td>
            <td>{{i.s5}}</td>
            <td>{{i.s6}}</td>
            <td>{{i.s1 |add:i.s2 |add:i.s3 |add:i.s4 |add:i.s5 |add:i.s6}}</td>
        </tr>
        {%endfor%}
    </tbody>
</table>
</body>
{%endblock%}
</div>
</html>

treisApp/templates/studentdetailsupdate.html
{%extends 'home.html'%}
{%block content%}
<html>
    <div class="container">    
        <h4 class="alert-info">Student Detials updated Successfully</h1>
    </div>
</html>
{%endblock%}